### PR TITLE
Sanitize carats from file name

### PR DESCRIPTION
**Pull request by workergnome**
When resizing images to fit, I use a resize string such as `resize_to: '230x250^'`.  The carat is not a valid character for online filenames, and breaks stuff.

Adding it to the sanitization whitelist.

### CODE REVIEW

**Comment by kubenstein** [comment]
hi @workergnome, first of all thank you for contribution. It is really kind of you! thank you! didnt know about `^` sign, for sure we need to sanitize it if this is valid imagemagick modifier. I would suggest to replace it with some valid string/char instead of stripping it completely. We do it for example with `<` replacing it with `lt`. all that to avoid names collision.
my suggestion is change '^' => 'c' what do you think?

**Comment by workergnome** [comment]
Sounds good. I'll modify my pull request. 



—
David Newbury
(773) 547-2272
david.newbury@gmail.com

**Comment by workergnome** [comment]
I've tweaked the pull request to handle this.

**Comment by kubenstein** [comment]
thank you!

**Pull request merged**
