### PR TITLE
Cache thumbnails in development.

### PR DESCRIPTION
**Pull request by noniq**
Thumbnails are saved to a cache directory after being created for the first time so that `Image#resize!` becomes a no-op on subsequent requests.

For cache invalidation, the filename of a cached thumbnail includes a SHA2 checksum of the original image. (The checksum is calculated on each request, but this is still noteably faster than resizing the original image, especially for larger image sizes.)

The cache directory defaults to 'tmp/simple-thumbnailer-cache' and can be customized via the `cache_dir` option.

There is no automatic removal of stale cached thumbnails. (Just manually remove the whole cache directory from time to time to get rid of old files.)

### CODE REVIEW

**Comment by kubenstein** [comment]
hi @noniq first of all thank you for contribution! caching in development was last thing that left for `middleman-simple-thumbnailer` to be complete. Will take one more look later today at your code and then merge it into master probably. thanks once again!

**Comment by noniq** [comment]
Thanks! Let me know if you have any suggestions or improvements for the code (it's kind of a version 0.1 – but it already proved useful in the project I'm currently working on).

**Comment by kubenstein** [comment]
i just looked into your code. it really speed things up! well made!
there are two things i want to discuss:
1) im not sure but i think [this line](https://github.com/kubenstein/middleman-simple-thumbnailer/pull/5/files#diff-9b5aa86b3d5f569da3e3301592868947R91) is not needed actually, but correct me if i missed something.
2) was wondering if file modification time would be just good enough. so instead of hashing file content lets compare fmod time, what do you think?

**Comment by noniq** [comment]
You're right about that line, I just added a commit that removes it.

I think modification time would work, too. It's a matter of personal taste – I personally don't like to rely on modification timestamps too much, so I tend to avoid them where possible. Relying on the actual content of a file gives me the cozy feeling of „I can do anything to this file – as long as I don't change it’s content, the cache remains fresh. And if I DO change the content, the cache is guaranteed to get stale, even if I somehow manage to change the content without altering the modification date“ :-)

**Comment by kubenstein** [comment]
yes you are right about file mod time. lets leave it with hash. merged! will take a look at other pending branch and then push all good stuff to rubygems. Thank you so much for contribution!

**Comment by noniq** [comment]
You’re welcome! Thanks for merging!

**Comment by kubenstein** [comment]
just to let you know i released v1.0.0, it is already on rubygems.. thx for contrib!

**Pull request merged**
