### PR TITLE
Support middleman v4.1

### PR DESCRIPTION
**Pull request by ymph**
Hello,

First thank you for this extension.
It is quite useful.
I made some changes to make it work with middleman 4.1 (4.1.10 right now)
Here are the modifications:

- I merged the pull request #11 from philiph/support-middleman-v4 (thank you @philiph)
- After (too) much debugging (and trial and errors), I determined that the reason the extension was not working in middleman 4.1 was the introduction of the parallel mode (c.f. https://github.com/middleman/middleman/blob/master/CHANGELOG.md#410). In parallel mode, the extension helpers are run in another process and therefore do not share the list of image to create in the "after_build" callback. So I devised this hack to use a temporary file (with read/write lock) to store the list of image. This is quite ugly and vastly inefficient, but seems to get the job done

Please tell me what you think, I am really eager to know your take on this issue and would like to see a better solution than the one I used.

Thank you,

Regards,

Yves-Marie Haussonne

### CODE REVIEW

**Comment by kubenstein** [comment]
hi @ymph, im so surprised and happy to see someone uses and wants to contribute. To be honest i switched stacks and i dont use middleman very often these days, thats why this repo is a bit rusty. Im really impressed you debugged and fix code and tests for version 4. really good job!
i think your solution with locked file is ok, if the problem is sharing resourced between threads we have to introduce some sharing mechanism. i would just a bit tweak key methods, so `store_resized_image` and `after_build` to hide details about sharing implementation and thus increase readability what actually is going on there - we save and read `resized_images` to shared storage. Maybe wrap code with method with block that internally write and read from file. we can collaborate.
About efficiency, luckily, we dont have to worry that much. during development i think your change wont drastically affect performance and during build, well, good to have stuff fast but building is one time operation not 100x per second so we can accept it but did you notice any drop in performance? i think it should be fine, version 3 of middleman wasnt using any parallelism and it was fast enough not to annoy at least in my projects.

Thx once again for all your time and effort!
Kuba

**Comment by ymph** [comment]
Hello,

First for information, and if this is ok for you to say, what stack are you using now ?

Next, I just pushed something that hide the implementation details at the extension(.rb) level.
It is what you meant in your message ?

About efficiency, I also is not really concerned in my project. I use this extension on a very little static site. It would certainly have been a lot more time efficient to create the resized image manually, than to hack this extension ! But when you start to scratch this itch...

Thank you,

Regards,

ymh

**Comment by kubenstein** [comment]
hi, thank you for all effort, i think extracting to separate class is really nice move, now all those locks and stuff are nicely hidden. I have to say i also were struggling with life cycle and the fact that the extension doesn't fit to middleman philosophy. Usually other extensions create files based on existing static files and static configuration, in our case information how to generate thumbnail is in the view so we have to build views first and that messes up everything. I also were experimenting to push all thru sprockets but sprockets is such a complicated tool that i wasnt able to do it in reasonably clean way.

---
Answering your question about stack, i moved to angular first and then to react. i built couple of sites on middleman to have all scss and minifications goodies, with angular frontend. my personal website is one of example. but i found a bit cumbersome to use ruby for managing js technologies so for most of my frontend stuff i switched to pure js builders, gulp at first for angular and then webpack for react stuff. i like to have api with data, for static pages its often static json file. but its easy to bind real server if project evolved and managing data needs to be more dynamic. For backend i still find ruby way cleaner and fun to code in.

---

So as you see i dont use this extension any more. You are really passionate and engaged person, if you want to overtake the project i would love to give it to good hands.

Kuba

**Comment by ymph** [comment]
Hello,

Thank you for the information on your new stack, it is always interesting to observe the technical choices of others.

Thank you for your kind words, I would be glad and honoured to help and make this extension live, so proceed as you see fit.

Regards,

ymh

**Comment by kubenstein** [comment]
hey hey, sorry for late reply, it would be really nice if you can overtake the project. i wonder how to do it tho. on github i guess you just keep your fork and ill put in readme that your repo is now official. The thing im not sure is how to transfer gem ownership on rubygems. do you have rubygems account?

**Pull request merged**
